[package]
name = "rusty_journal"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[dependencies]
structopt = "0.3"
serde_json = "1.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"